/**
 * examples2_days_201_250.js — 전치사 핵심 이미지 두 번째 예문 (Days 201~205)
 */

Object.assign(EXAMPLES2, {

  // Day 201 — 전치사 AT
  '201_0':  { example2: "The rescue dog felt completely at home in her new family within just a few days.",          example2Kr: "구조견은 불과 며칠 만에 새 가족 안에서 완전히 편안함을 느꼈다." },
  '201_1':  { example2: "Different social and economic forces are at work reshaping cities around the world.",       example2Kr: "다양한 사회적·경제적 힘들이 전 세계 도시를 변화시키는 데 작용하고 있다." },
  '201_2':  { example2: "At school, she discovered her passion for mathematics and went on to study engineering.",   example2Kr: "학교에서 그녀는 수학에 대한 열정을 발견했고 공학을 공부하러 나아갔다." },
  '201_3':  { example2: "Please stop what you are doing and come to the reception area at once.",                    example2Kr: "하던 일을 멈추고 즉시 리셉션 지역으로 와 주십시오." },
  '201_4':  { example2: "At last, the two nations reached a historic peace agreement after decades of tension.",     example2Kr: "마침내 두 국가는 수십 년간의 긴장 끝에 역사적인 평화 협정에 이르렀다." },
  '201_5':  { example2: "The apartment should have at least two bedrooms for the family to live comfortably.",       example2Kr: "가족이 편안하게 살려면 아파트에 최소 두 개의 침실이 있어야 한다." },
  '201_6':  { example2: "The meeting will take at most thirty minutes if we all stick to the agenda.",              example2Kr: "우리 모두가 의제를 지킨다면 회의는 기껏해야 30분이 걸릴 것이다." },
  '201_7':  { example2: "At first glance, the two paintings appear identical, but subtle differences exist.",        example2Kr: "처음 볼 때는 두 그림이 같아 보이지만, 미묘한 차이점이 존재한다." },
  '201_8':  { example2: "Older adults with chronic conditions are more at risk during the flu season.",             example2Kr: "만성 질환이 있는 노인들은 독감 시즌에 더 위험에 처한다." },
  '201_9':  { example2: "The company's entire reputation is at stake following the data breach scandal.",           example2Kr: "데이터 유출 스캔들에 따라 회사의 전체 명성이 위태롭다." },
  '201_10': { example2: "Both drivers were found to be partially at fault for ignoring the traffic sign.",          example2Kr: "두 운전자 모두 교통 표지를 무시한 것에 부분적으로 잘못이 있는 것으로 밝혀졌다." },
  '201_11': { example2: "Security checks were conducted at random to maintain unpredictability in the system.",     example2Kr: "보안 점검은 시스템의 예측 불가능성을 유지하기 위해 무작위로 실시되었다." },
  '201_12': { example2: "The escaped zoo animal remained at large in the surrounding forest for several hours.",    example2Kr: "탈출한 동물원 동물은 몇 시간 동안 주변 숲 속에서 도주 중이었다." },
  '201_13': { example2: "With exams at hand, students are spending late nights reviewing all of their notes.",      example2Kr: "시험이 임박하자 학생들은 모든 노트를 복습하며 늦은 밤을 보내고 있다." },
  '201_14': { example2: "At heart, she remains a creative artist even though she now works in corporate finance.",  example2Kr: "마음속으로는, 그녀가 지금 기업 재무에서 일하고 있지만 창의적인 예술가로 남아 있다." },
  '201_15': { example2: "The witness described every detail of the incident at length to the investigating officers.", example2Kr: "증인은 수사 담당자들에게 사건의 모든 세부 사항을 자세히 설명했다." },
  '201_16': { example2: "When the question was posed in French, the student was completely at a loss.",             example2Kr: "질문이 프랑스어로 제시되었을 때, 학생은 완전히 어쩔 줄 몰랐다." },
  '201_17': { example2: "Deep breathing exercises can help put anxious speakers at ease before a presentation.",    example2Kr: "심호흡 운동이 발표 전에 불안한 발표자들을 편안하게 하는 데 도움이 된다." },
  '201_18': { example2: "Without new investment, the company can at best maintain its current market share.",       example2Kr: "새로운 투자 없이는 회사가 기껏해야 현재의 시장 점유율을 유지할 수 있다." },
  '201_19': { example2: "At worst, the software glitch will require a full system restart to be resolved.",         example2Kr: "최악의 경우, 소프트웨어 결함을 해결하려면 전체 시스템을 재시작해야 할 것이다." },

  // Day 202 — 전치사 ON
  '202_0':  { example2: "Delivering the presentation on time showed the client that we respect their schedule.",    example2Kr: "제시간에 발표를 전달한 것이 우리가 고객의 일정을 존중한다는 것을 보여주었다." },
  '202_1':  { example2: "She left the door unlocked on purpose so that her roommate could get in easily.",          example2Kr: "그녀는 룸메이트가 쉽게 들어올 수 있도록 의도적으로 문을 잠그지 않았다." },
  '202_2':  { example2: "On the whole, the transition to the new software system went more smoothly than expected.", example2Kr: "전반적으로, 새 소프트웨어 시스템으로의 전환은 예상보다 더 원활하게 진행되었다." },
  '202_3':  { example2: "The CEO presented the award on behalf of the entire software development team.",           example2Kr: "CEO가 전체 소프트웨어 개발팀을 대신하여 상을 수여했다." },
  '202_4':  { example2: "The treatment did not make him feel worse; on the contrary, he improved visibly.",         example2Kr: "치료가 그를 더 안 좋게 만들지 않았다; 오히려 그는 눈에 띄게 호전되었다." },
  '202_5':  { example2: "Exploring a new city on foot is the best way to discover its hidden gems.",               example2Kr: "새 도시를 걸어서 탐험하는 것이 숨겨진 보석들을 발견하는 가장 좋은 방법이다." },
  '202_6':  { example2: "All summer clothing will go on sale at the end of August to clear seasonal stock.",        example2Kr: "계절 재고를 정리하기 위해 모든 여름 의류가 8월 말에 할인에 들어갈 것이다." },
  '202_7':  { example2: "A security guard is on duty around the clock at the main entrance of the building.",       example2Kr: "건물 정문에는 보안 요원이 24시간 내내 근무하고 있다." },
  '202_8':  { example2: "The new printing system produces customised books on demand, reducing warehouse costs.",   example2Kr: "새 인쇄 시스템은 주문에 따라 맞춤형 책을 생산하여 창고 비용을 줄인다." },
  '202_9':  { example2: "We spotted a beautiful waterfall on the way up to the mountain summit.",                   example2Kr: "우리는 산 정상으로 올라가는 길에 아름다운 폭포를 발견했다." },
  '202_10': { example2: "Solar energy is environmentally clean; on the other hand, installation costs remain high.", example2Kr: "태양 에너지는 환경적으로 깨끗하지만, 반면에 설치 비용은 여전히 높다." },
  '202_11': { example2: "Air traffic controllers went on strike, causing widespread flight cancellations across Europe.", example2Kr: "항공 교통 관제사들이 파업에 돌입하여 유럽 전역에 대규모 항공편 취소가 발생했다." },
  '202_12': { example2: "A revolutionary new drug therapy is currently on trial at three major hospitals in the country.", example2Kr: "혁신적인 신약 치료법이 현재 국내 세 개 주요 병원에서 임상 시험 중이다." },
  '202_13': { example2: "The outdoor rally was relocated indoors on account of the unexpected heavy snowfall.",     example2Kr: "야외 집회는 예상치 못한 폭설 때문에 실내로 장소가 변경되었다." },
  '202_14': { example2: "He eats breakfast on the go every morning because he always runs a little late.",          example2Kr: "그는 항상 조금 늦기 때문에 매일 아침 이동하면서 아침을 먹는다." },
  '202_15': { example2: "The manager made the critical decision on the spot without needing further consultation.", example2Kr: "관리자는 추가 상담이 필요 없이 즉석에서 중요한 결정을 내렸다." },
  '202_16': { example2: "The children were on edge all morning, anxiously waiting to find out their test results.",  example2Kr: "아이들은 시험 결과를 알기 위해 불안하게 기다리며 오전 내내 초조했다." },
  '202_17': { example2: "Phase two of the highway expansion project is running on schedule and within budget.",      example2Kr: "고속도로 확장 프로젝트의 2단계가 예정대로 예산 내에서 진행되고 있다." },
  '202_18': { example2: "On average, it takes about 66 days to form a new habit consistently, not 21.",             example2Kr: "평균적으로, 새로운 습관을 일관되게 형성하는 데는 21일이 아닌 약 66일이 걸린다." },
  '202_19': { example2: "On second thought, I will take the earlier flight to avoid any risky connection times.",   example2Kr: "다시 생각해보니, 위험한 환승 시간을 피하기 위해 더 이른 항공편을 탈 것이다." },

  // Day 203 — 전치사 IN
  '203_0':  { example2: "Contact the embassy in advance to find out exactly what documents are required for entry.", example2Kr: "입국에 필요한 서류를 정확히 알아보기 위해 사전에 대사관에 연락하세요." },
  '203_1':  { example2: "In addition to completing the training, new drivers must also pass a practical road test.", example2Kr: "교육 이수 외에도 신규 운전자들은 실기 도로 시험도 통과해야 한다." },
  '203_2':  { example2: "The ancient painting was, in fact, a clever forgery that fooled art museums for decades.", example2Kr: "그 고대 그림은 사실 수십 년 동안 미술관을 속인 교묘한 위작이었다." },
  '203_3':  { example2: "In general, people who sleep well consistently tend to perform better at cognitive tasks.", example2Kr: "일반적으로, 잠을 충분히 자는 사람들이 인지적 과제에서 더 잘 수행하는 경향이 있다." },
  '203_4':  { example2: "The two rival companies actually have more in common than their leaders publicly admit.",   example2Kr: "두 경쟁 회사는 사실 경영진이 공개적으로 인정하는 것보다 공통점이 더 많다." },
  '203_5':  { example2: "The senior nurse was left in charge of the entire ward when the doctor was called away.",  example2Kr: "의사가 불려 나가자 수석 간호사가 전체 병동을 맡게 되었다." },
  '203_6':  { example2: "Could you explain your entire research methodology in detail for the committee please?",   example2Kr: "위원회를 위해 전체 연구 방법론을 자세히 설명해 주시겠어요?" },
  '203_7':  { example2: "New emissions rules will be in effect across the entire transport sector from next year.",  example2Kr: "새 배출 규정이 내년부터 전체 운송 부문에 걸쳐 유효하게 된다." },
  '203_8':  { example2: "Better nutrition leads to improved health, which in turn boosts productivity at work.",     example2Kr: "더 나은 영양은 건강 향상으로 이어지고, 이는 결과적으로 업무 생산성을 높인다." },
  '203_9':  { example2: "In terms of environmental impact, cycling is superior to any form of motorised transport.", example2Kr: "환경적 영향 측면에서 자전거 타기는 어떤 형태의 자동차 교통보다 우수하다." },
  '203_10': { example2: "In order to qualify, all candidates must hold a relevant degree and three years' experience.", example2Kr: "자격을 갖추려면 모든 지원자들이 관련 학위와 3년間의 경력을 보유해야 한다." },
  '203_11': { example2: "Eliminating processed foods from the diet is difficult at first but rewarding in the long run.", example2Kr: "가공식품을 식단에서 제거하는 것은 처음에는 어렵지만 장기적으로는 보람 있다." },
  '203_12': { example2: "Northern summers are short and intense; in contrast, the south enjoys a much longer season.", example2Kr: "북부의 여름은 짧고 강렬하다; 대조적으로, 남부는 훨씬 더 긴 계절을 즐긴다." },
  '203_13': { example2: "In brief, our recommendation is to expand into the Asian market during next quarter.",      example2Kr: "간략히, 저희의 권고는 다음 분기에 아시아 시장으로 확장하는 것입니다." },
  '203_14': { example2: "If in doubt about the authenticity of an email, do not click any of the embedded links.",  example2Kr: "이메일의 진위 여부에 의심이 가면, 포함된 링크 중 어느 것도 클릭하지 마세요." },
  '203_15': { example2: "Peace negotiations between the two nations are currently in progress in Geneva.",           example2Kr: "두 국가 사이의 평화 협상이 현재 제네바에서 진행 중이다." },
  '203_16': { example2: "The airline found itself in trouble when passengers began filing mass compensation claims.", example2Kr: "승객들이 대규모 보상 청구를 시작하자 항공사는 곤경에 처하게 되었다." },
  '203_17': { example2: "Local charities distribute emergency food parcels to families in need every single week.",  example2Kr: "지역 자선단체들이 매주 도움이 필요한 가족들에게 긴급 식품 꾸러미를 나눠준다." },
  '203_18': { example2: "All emergency procedures must be in place before the new facility can open to the public.", example2Kr: "모든 비상 절차가 갖춰져야 새 시설이 대중에게 개방될 수 있다." },
  '203_19': { example2: "In theory, working from home increases productivity; in practice, results vary greatly.",   example2Kr: "이론적으로는 재택근무가 생산성을 높이지만, 실제로는 결과가 크게 다르다." },

  // Day 204 — 전치사 FOR & TO
  '204_0':  { example2: "New users can access all the premium features completely for free during the first month.", example2Kr: "새 사용자들은 첫 달 동안 모든 프리미엄 기능에 완전히 무료로 접근할 수 있다." },
  '204_1':  { example2: "He gave up smoking for good after the doctor warned him about his deteriorating heart condition.", example2Kr: "의사가 악화되는 심장 질환에 대해 경고한 후 그는 영원히 흡연을 끊었다." },
  '204_2':  { example2: "Travellers often take passport freedom for granted until they face strict visa restrictions.", example2Kr: "여행자들은 엄격한 비자 제한에 직면할 때까지 여권 자유를 당연하게 여기는 경우가 많다." },
  '204_3':  { example2: "Mindfulness practices, for instance meditation and slow breathing, reduce anxiety effectively.", example2Kr: "예를 들어 명상과 느린 호흡 같은 마음챙김 연습이 불안을 효과적으로 줄인다." },
  '204_4':  { example2: "For now, the border remains open, though the political situation may change swiftly.",       example2Kr: "당분간은 국경이 열려 있지만, 정치적 상황은 신속하게 변할 수 있다." },
  '204_5':  { example2: "For the time being, we will continue using the old system until the upgrade is complete.",  example2Kr: "당분간, 업그레이드가 완료될 때까지 기존 시스템을 계속 사용할 것이다." },
  '204_6':  { example2: "For once, the coach had nothing to criticise after the team's truly flawless performance.", example2Kr: "이번만은, 팀의 진정으로 흠잡을 데 없는 경기 후 코치가 비판할 것이 없었다." },
  '204_7':  { example2: "We cannot finalise the plans for sure until the investor officially confirms the funding.",  example2Kr: "투자자가 공식적으로 자금을 확인할 때까지 계획을 확실히 결정할 수 없다." },
  '204_8':  { example2: "I haven't been to the theatre for ages — probably not since long before the lockdown.",     example2Kr: "극장에 간 지 오랫동안 됐다 — 아마 봉쇄 훨씬 전부터 안 간 것 같다." },
  '204_9':  { example2: "This time the champion made it clear she was returning to the sport for keeps.",            example2Kr: "이번에 챔피언은 자신이 그 스포츠에 영구적으로 복귀한다는 것을 분명히 했다." },
  '204_10': { example2: "To date, more than fifty countries have ratified the landmark international climate accord.", example2Kr: "현재까지 50개 이상의 국가가 역사적인 국제 기후 협약을 비준했다." },
  '204_11': { example2: "To begin with, review all the existing data carefully before proposing any new solutions.",  example2Kr: "우선 새로운 해결책을 제안하기 전에 기존의 모든 데이터를 신중하게 검토하라." },
  '204_12': { example2: "The director's instructions were firm and to the point: finish the report by Friday noon.", example2Kr: "감독의 지시는 확고하고 요점에 맞았다: 금요일 정오까지 보고서를 끝내라." },
  '204_13': { example2: "The engineers rebooted the server multiple times to no avail before discovering the fault.", example2Kr: "엔지니어들이 결함을 발견하기 전에 서버를 여러 번 재부팅했지만 소용없었다." },
  '204_14': { example2: "To some extent, luck plays a role in career success, but consistent preparation matters more.", example2Kr: "어느 정도는, 운이 경력 성공에 역할을 하지만, 일관된 준비가 더 중요하다." },
  '204_15': { example2: "To the scientists' surprise, the plant continued to grow without any sunlight for two weeks.", example2Kr: "과학자들의 놀라움에도, 식물은 2주 동안 햇빛 없이 계속 자랐다." },
  '204_16': { example2: "To the manager's knowledge, no confidential data was ever shared outside the organisation.",  example2Kr: "관리자가 아는 한, 기밀 데이터는 조직 외부에 공유된 적이 없다." },
  '204_17': { example2: "He is meticulous to a fault, checking every single line of code before making a submission.", example2Kr: "그는 지나칠 정도로 꼼꼼하여 제출하기 전에 모든 코드 한 줄씩 확인한다." },
  '204_18': { example2: "Waking up to find the entire production database had been deleted was alarming, to say the least.", example2Kr: "전체 운영 데이터베이스가 삭제된 것을 알게 되는 것은 최소한으로 말해도 충격적이었다." },
  '204_19': { example2: "The public apology made things worse, and to make matters worse, sales also dropped sharply.", example2Kr: "공개 사과가 상황을 악화시켰고, 설상가상으로 매출도 급격히 떨어졌다." },

  // Day 205 — 전치사 BY / WITH / FROM
  '205_0':  { example2: "She ran into her old school friend by chance in a small independent bookshop in Edinburgh.", example2Kr: "그녀는 에든버러의 작은 독립 서점에서 우연히 옛 학교 친구를 만났다." },
  '205_1':  { example2: "This year's harvest is by far the largest that the agricultural region has recorded in decades.", example2Kr: "올해 수확량은 단연코 그 농업 지역이 수십 년 만에 기록한 가장 많은 양이다." },
  '205_2':  { example2: "Learning poetry by heart sharpens memory and deepens an appreciation of language.",          example2Kr: "시를 암기하는 것은 기억력을 날카롭게 하고 언어에 대한 감각을 깊게 한다." },
  '205_3':  { example2: "The technician accidentally deleted the entire production database by mistake, causing a major outage.", example2Kr: "기술자가 실수로 전체 운영 데이터베이스를 삭제하여 대규모 중단이 발생했다." },
  '205_4':  { example2: "The discovery of a single fossil is by no means sufficient evidence for classifying a new species.", example2Kr: "단 하나의 화석 발견은 새 종을 분류하기 위한 충분한 증거가 결코 아니다." },
  '205_5':  { example2: "If you would like to raise any concerns publicly at today's meeting, by all means do so.",   example2Kr: "오늘 회의에서 어떤 우려 사항이든 공개적으로 제기하고 싶다면 물론 그렇게 하세요." },
  '205_6':  { example2: "By now, the package should have arrived; please check your online tracking number.",         example2Kr: "지금쯤은 소포가 도착했을 것이니, 온라인 추적 번호를 확인하세요." },
  '205_7':  { example2: "The museum curator restored the heavily damaged oil painting with extraordinary care.",      example2Kr: "박물관 큐레이터는 심하게 손상된 유화를 특별한 주의를 기울여 복원했다." },
  '205_8':  { example2: "Thanks to months of intense practice, she delivered her entire keynote speech with ease.",   example2Kr: "몇 달간의 집중적인 연습 덕분에 그녀는 전체 기조연설을 수월하게 전달했다." },
  '205_9':  { example2: "With regard to the invoice discrepancy, our accounts team is investigating and will respond soon.", example2Kr: "청구서 불일치에 관하여, 우리 회계팀이 조사 중이며 곧 답변할 것이다." },
  '205_10': { example2: "With respect to the proposed merger, the full board will vote at the next scheduled meeting.", example2Kr: "제안된 합병에 관하여, 전체 이사회가 다음 예정된 회의에서 투표할 것이다." },
  '205_11': { example2: "The new vaccine is without doubt a landmark breakthrough in fighting infectious diseases.",    example2Kr: "새 백신은 의심할 여지 없이 전염병과의 싸움에서 획기적인 돌파구이다." },
  '205_12': { example2: "All quality control checks must be completed without fail before every product shipment.",   example2Kr: "품질 관리 점검은 모든 제품 출하 전에 반드시 완료되어야 한다." },
  '205_13': { example2: "After months of rigorous preparation, the candidate passed the bar exam with flying colors.", example2Kr: "몇 달간의 엄격한 준비 끝에, 지원자는 변호사 시험에 눈부신 성과로 합격했다." },
  '205_14': { example2: "From now on, any decision above a certain budget limit will require full board approval.",   example2Kr: "이제부터, 특정 예산 한도 이상의 모든 결정은 전체 이사회의 승인이 필요하다." },
  '205_15': { example2: "The development team rewrote the entire codebase completely from scratch to remove legacy bugs.", example2Kr: "개발팀이 레거시 버그를 제거하기 위해 전체 코드베이스를 처음부터 완전히 다시 작성했다." },
  '205_16': { example2: "From time to time, unexpected opportunities arise that can completely change your career path.", example2Kr: "때때로, 당신의 경력 경로를 완전히 바꿀 수 있는 예상치 못한 기회들이 나타난다." },
  '205_17': { example2: "The athlete was dressed proudly in the national team's colours from head to toe on match day.", example2Kr: "선수는 경기일에 머리부터 발끝까지 국가대표팀 색깔로 자랑스럽게 차려입었다." },
  '205_18': { example2: "Apart from the weather, everything about our holiday in Japan was absolutely perfect.",       example2Kr: "날씨를 제외하고, 일본에서의 우리 휴가의 모든 것이 완전히 완벽했다." },
  '205_19': { example2: "The final exam results were far from what the students had hoped for after all their revision.", example2Kr: "최종 시험 결과는 모든 복습을 한 후 학생들이 기대했던 것과는 전혀 달랐다." }

});
