/**
 * examples2.js — 두 번째 예문 데이터 (Day 1~5)
 * 키: '{day}_{index}' (0-based)
 */
const EXAMPLES2 = {
  // Day 1 — 생활회화 기초 동사
  '1_0':  { example: "He greeted his neighbors every morning.", exampleKr: "그는 매일 아침 이웃들에게 인사했다." },
  '1_1':  { example: "She ordered a salad and a glass of water.", exampleKr: "그녀는 샐러드와 물 한 잔을 주문했다." },
  '1_2':  { example: "I reserved a hotel room for the weekend.", exampleKr: "주말을 위해 호텔 방을 예약했다." },
  '1_3':  { example: "My friend recommended this restaurant.", exampleKr: "친구가 이 식당을 추천해 줬다." },
  '1_4':  { example: "I prefer working in the morning.", exampleKr: "나는 아침에 일하는 것을 선호한다." },
  '1_5':  { example: "Would you mind opening the window?", exampleKr: "창문을 열어도 될까요?" },
  '1_6':  { example: "We appreciate your patience.", exampleKr: "기다려 주셔서 감사합니다." },
  '1_7':  { example: "He apologized for the misunderstanding.", exampleKr: "그는 오해에 대해 사과했다." },
  '1_8':  { example: "She suggested trying a different approach.", exampleKr: "그녀는 다른 접근 방식을 시도해보자고 제안했다." },
  '1_9':  { example: "We all agreed to meet at 7 pm.", exampleKr: "우리는 모두 오후 7시에 만나기로 동의했다." },
  '1_10': { example: "I disagree with that decision.", exampleKr: "나는 그 결정에 동의하지 않는다." },
  '1_11': { example: "Can you manage to arrive by noon?", exampleKr: "정오까지 도착할 수 있나요?" },
  '1_12': { example: "Let me check the schedule first.", exampleKr: "먼저 일정을 확인해 볼게요." },
  '1_13': { example: "He can handle the pressure well.", exampleKr: "그는 압박을 잘 처리할 수 있다." },
  '1_14': { example: "She arranged the flowers beautifully.", exampleKr: "그녀는 꽃을 아름답게 배열했다." },
  '1_15': { example: "Can I borrow your umbrella?", exampleKr: "우산을 빌려도 될까요?" },
  '1_16': { example: "He lent his car to his brother.", exampleKr: "그는 동생에게 차를 빌려줬다." },
  '1_17': { example: "Don't miss this great opportunity.", exampleKr: "이 좋은 기회를 놓치지 마세요." },
  '1_18': { example: "I'll wait for you outside the building.", exampleKr: "건물 밖에서 기다릴게요." },
  '1_19': { example: "Don't hurry — we have plenty of time.", exampleKr: "서두르지 마세요 — 시간이 충분해요." },

  // Day 2 — 생활회화 핵심 표현
  '2_0':  { example: "I'll definitely call you back later.", exampleKr: "나중에 꼭 다시 전화할게요." },
  '2_1':  { example: "Actually, I've been there before.", exampleKr: "사실, 나는 전에 거기 가본 적이 있다." },
  '2_2':  { example: "Basically, the plan is to save money.", exampleKr: "기본적으로, 계획은 돈을 절약하는 것이다." },
  '2_3':  { example: "You're exactly right about that.", exampleKr: "그 점에 대해 당신이 정확히 맞습니다." },
  '2_4':  { example: "She'll probably be home by 6.", exampleKr: "그녀는 아마 6시까지 집에 올 것이다." },
  '2_5':  { example: "Honestly, I need more time to decide.", exampleKr: "솔직히, 나는 결정하는 데 더 많은 시간이 필요해." },
  '2_6':  { example: "The answer is simply not good enough.", exampleKr: "그 대답은 단순히 충분하지 않다." },
  '2_7':  { example: "I especially enjoyed the last chapter.", exampleKr: "나는 특히 마지막 장이 마음에 들었다." },
  '2_8':  { example: "I haven't been sleeping well recently.", exampleKr: "나는 최근에 잠을 잘 못 자고 있다." },
  '2_9':  { example: "He finally got the job he wanted.", exampleKr: "그는 마침내 원하던 직장을 얻었다." },
  '2_10': { example: "The lights suddenly went out.", exampleKr: "갑자기 불이 꺼졌다." },
  '2_11': { example: "I nearly fell asleep during the lecture.", exampleKr: "나는 강의 중에 거의 잠들 뻔했다." },
  '2_12': { example: "She clearly explained the instructions.", exampleKr: "그녀는 지침을 명확하게 설명했다." },
  '2_13': { example: "I fully support your decision.", exampleKr: "나는 당신의 결정을 완전히 지지합니다." },
  '2_14': { example: "He hardly ever complains.", exampleKr: "그는 거의 불평하지 않는다." },
  '2_15': { example: "Take the train instead of driving.", exampleKr: "운전하는 대신 기차를 타세요." },
  '2_16': { example: "Meanwhile, the team was still working.", exampleKr: "그동안, 팀은 여전히 일하고 있었다." },
  '2_17': { example: "Leave now, otherwise you'll miss it.", exampleKr: "지금 떠나세요, 그렇지 않으면 놓칠 거예요." },
  '2_18': { example: "It's a long way; however, it's worth it.", exampleKr: "먼 길이지만 그만한 가치가 있다." },
  '2_19': { example: "She trained hard and therefore won.", exampleKr: "그녀는 열심히 훈련했고 따라서 우승했다." },

  // Day 3 — 고등학교 필수 동사 I
  '3_0':  { example: "He abandoned his old habits for good.", exampleKr: "그는 예전 습관을 완전히 버렸다." },
  '3_1':  { example: "The law was abolished after protests.", exampleKr: "항의 후에 그 법이 폐지되었다." },
  '3_2':  { example: "Children absorb new languages quickly.", exampleKr: "아이들은 새로운 언어를 빠르게 습득한다." },
  '3_3':  { example: "Technology has accelerated our lives.", exampleKr: "기술은 우리의 삶을 가속화시켰다." },
  '3_4':  { example: "He acknowledged the team's hard work.", exampleKr: "그는 팀의 노고를 인정했다." },
  '3_5':  { example: "She acquired the language in just one year.", exampleKr: "그녀는 단 1년 만에 그 언어를 습득했다." },
  '3_6':  { example: "The vaccine activates the immune system.", exampleKr: "백신은 면역 체계를 활성화한다." },
  '3_7':  { example: "Everyone admires his dedication.", exampleKr: "모든 사람이 그의 헌신에 감탄한다." },
  '3_8':  { example: "Lack of sleep affects your concentration.", exampleKr: "수면 부족은 집중력에 영향을 미친다." },
  '3_9':  { example: "Pets are not allowed in this area.", exampleKr: "이 지역에서는 반려동물이 허용되지 않는다." },
  '3_10': { example: "The plan was altered at the last minute.", exampleKr: "계획은 마지막 순간에 변경되었다." },
  '3_11': { example: "The news amazed everyone in the room.", exampleKr: "그 소식은 방 안의 모든 사람을 놀라게 했다." },
  '3_12': { example: "She avoids crowds whenever possible.", exampleKr: "그녀는 가능하면 군중을 피한다." },
  '3_13': { example: "He blamed the traffic for his lateness.", exampleKr: "그는 늦은 것에 대해 교통을 탓했다." },
  '3_14': { example: "A good breakfast boosts your productivity.", exampleKr: "좋은 아침 식사는 생산성을 높인다." },
  '3_15': { example: "He calculated the distance carefully.", exampleKr: "그는 거리를 신중하게 계산했다." },
  '3_16': { example: "The camera captured the perfect moment.", exampleKr: "카메라는 완벽한 순간을 포착했다." },
  '3_17': { example: "His recklessness caused an accident.", exampleKr: "그의 무모함이 사고를 야기했다." },
  '3_18': { example: "She claimed the award was unfair.", exampleKr: "그녀는 그 상이 불공정하다고 주장했다." },
  '3_19': { example: "Combine flour, eggs, and milk to make batter.", exampleKr: "밀가루, 달걀, 우유를 합쳐 반죽을 만드세요." },

  // Day 4 — TOEIC 빈출 명사 I
  '4_0':  { example: "The agenda for today's meeting has changed.", exampleKr: "오늘 회의의 안건이 변경되었다." },
  '4_1':  { example: "Her proposal received quick approval.", exampleKr: "그녀의 제안은 빠른 승인을 받았다." },
  '4_2':  { example: "The report's attachment includes all data.", exampleKr: "보고서의 첨부 파일에 모든 데이터가 포함된다." },
  '4_3':  { example: "The bank opened a new branch downtown.", exampleKr: "은행은 시내에 새 지점을 열었다." },
  '4_4':  { example: "We set a tight budget for the project.", exampleKr: "우리는 프로젝트에 엄격한 예산을 설정했다." },
  '4_5':  { example: "The best candidate was hired immediately.", exampleKr: "가장 적합한 지원자가 즉시 채용되었다." },
  '4_6':  { example: "The cargo was delayed at the port.", exampleKr: "화물은 항구에서 지연되었다." },
  '4_7':  { example: "Our main client requested a meeting.", exampleKr: "주요 고객이 회의를 요청했다." },
  '4_8':  { example: "The complaint was handled professionally.", exampleKr: "불만은 전문적으로 처리되었다." },
  '4_9':  { example: "Both parties signed the contract.", exampleKr: "양측이 계약서에 서명했다." },
  '4_10': { example: "We must meet the deadline without fail.", exampleKr: "우리는 반드시 마감 기한을 맞춰야 한다." },
  '4_11': { example: "Free delivery is available on orders over $50.", exampleKr: "50달러 이상 주문 시 무료 배송이 가능하다." },
  '4_12': { example: "The IT department solved the issue quickly.", exampleKr: "IT 부서가 문제를 빠르게 해결했다." },
  '4_13': { example: "Weekend discount is available for members.", exampleKr: "주말 할인은 회원에게 제공됩니다." },
  '4_14': { example: "Keep all financial documents organized.", exampleKr: "모든 재정 서류를 정리해 두세요." },
  '4_15': { example: "Submit an expense report every month.", exampleKr: "매달 경비 보고서를 제출하세요." },
  '4_16': { example: "The new facility opens next month.", exampleKr: "새 시설은 다음 달에 문을 연다." },
  '4_17': { example: "Please provide feedback on the product.", exampleKr: "제품에 대한 피드백을 제공해 주세요." },
  '4_18': { example: "Visit our headquarters for a tour.", exampleKr: "견학을 위해 본사를 방문하세요." },
  '4_19': { example: "The invoice must be paid within 30 days.", exampleKr: "청구서는 30일 이내에 납부해야 한다." },

  // Day 5 — TOEIC 빈출 동사 I
  '5_0':  { example: "The venue can accommodate a large audience.", exampleKr: "그 장소는 많은 관중을 수용할 수 있다." },
  '5_1':  { example: "The team accomplished a remarkable feat.", exampleKr: "팀은 놀라운 성과를 달성했다." },
  '5_2':  { example: "The report addresses several key issues.", exampleKr: "보고서는 몇 가지 핵심 문제를 다룬다." },
  '5_3':  { example: "He adjusted his schedule to fit the meeting.", exampleKr: "그는 회의에 맞게 일정을 조정했다." },
  '5_4':  { example: "The winner was announced at the ceremony.", exampleKr: "수상자는 시상식에서 발표되었다." },
  '5_5':  { example: "The bank authorized the transaction.", exampleKr: "은행이 거래를 승인했다." },
  '5_6':  { example: "The event was cancelled at short notice.", exampleKr: "행사가 짧은 예고 기간 후 취소되었다." },
  '5_7':  { example: "They charge a fee for late returns.", exampleKr: "그들은 연체 반납에 수수료를 청구한다." },
  '5_8':  { example: "He completed the marathon in record time.", exampleKr: "그는 기록적인 시간에 마라톤을 완주했다." },
  '5_9':  { example: "Students must comply with school rules.", exampleKr: "학생들은 학교 규칙을 준수해야 한다." },
  '5_10': { example: "He confirmed the appointment by phone.", exampleKr: "그는 전화로 약속을 확인했다." },
  '5_11': { example: "He coordinates between the two teams.", exampleKr: "그는 두 팀 사이를 조율한다." },
  '5_12': { example: "The forms were distributed to all students.", exampleKr: "양식은 모든 학생들에게 배포되었다." },
  '5_13': { example: "The expert estimated the damage at $5,000.", exampleKr: "전문가는 피해액을 5천 달러로 추산했다." },
  '5_14': { example: "Let's finalize the contract this week.", exampleKr: "이번 주에 계약을 마무리합시다." },
  '5_15': { example: "Please forward the message to everyone.", exampleKr: "모든 사람에게 메시지를 전달해 주세요." },
  '5_16': { example: "They hired an experienced consultant.", exampleKr: "그들은 경험 많은 컨설턴트를 고용했다." },
  '5_17': { example: "An inspector was sent to inspect the site.", exampleKr: "검사관이 현장 점검을 위해 보내졌다." },
  '5_18': { example: "We will notify you when it's ready.", exampleKr: "준비가 되면 알려드리겠습니다." },
  '5_19': { example: "The bank will process your request shortly.", exampleKr: "은행이 곧 귀하의 요청을 처리할 것입니다." }
};
