/**
 * examples2_days_201_250.js — 전치사 핵심 이미지 두 번째 예문 (Days 201~205)
 */

Object.assign(EXAMPLES2, {

  // Day 201 — 전치사 AT
  '201_0':  { example2: "The rescue dog felt completely at home in her new family within just a few days.",          example2Kr: "구조견은 불과 며칠 만에 새 가족 안에서 완전히 편안함을 느꼈다." },
  '201_1':  { example2: "Different social and economic forces are at work reshaping cities around the world.",       example2Kr: "다양한 사회적·경제적 힘들이 전 세계 도시를 변화시키는 데 작용하고 있다." },
  '201_2':  { example2: "At school, she discovered her passion for mathematics and went on to study engineering.",   example2Kr: "학교에서 그녀는 수학에 대한 열정을 발견했고 공학을 공부하러 나아갔다." },
  '201_3':  { example2: "Please stop what you are doing and come to the reception area at once.",                    example2Kr: "하던 일을 멈추고 즉시 리셉션 지역으로 와 주십시오." },
  '201_4':  { example2: "At last, the two nations reached a historic peace agreement after decades of tension.",     example2Kr: "마침내 두 국가는 수십 년간의 긴장 끝에 역사적인 평화 협정에 이르렀다." },
  '201_5':  { example2: "The apartment should have at least two bedrooms for the family to live comfortably.",       example2Kr: "가족이 편안하게 살려면 아파트에 최소 두 개의 침실이 있어야 한다." },
  '201_6':  { example2: "The meeting will take at most thirty minutes if we all stick to the agenda.",              example2Kr: "우리 모두가 의제를 지킨다면 회의는 기껏해야 30분이 걸릴 것이다." },
  '201_7':  { example2: "At first glance, the two paintings appear identical, but subtle differences exist.",        example2Kr: "처음 볼 때는 두 그림이 같아 보이지만, 미묘한 차이점이 존재한다." },
  '201_8':  { example2: "Older adults with chronic conditions are more at risk during the flu season.",             example2Kr: "만성 질환이 있는 노인들은 독감 시즌에 더 위험에 처한다." },
  '201_9':  { example2: "The company's entire reputation is at stake following the data breach scandal.",           example2Kr: "데이터 유출 스캔들에 따라 회사의 전체 명성이 위태롭다." },
  '201_10': { example2: "Both drivers were found to be partially at fault for ignoring the traffic sign.",          example2Kr: "두 운전자 모두 교통 표지를 무시한 것에 부분적으로 잘못이 있는 것으로 밝혀졌다." },
  '201_11': { example2: "Security checks were conducted at random to maintain unpredictability in the system.",     example2Kr: "보안 점검은 시스템의 예측 불가능성을 유지하기 위해 무작위로 실시되었다." },
  '201_12': { example2: "The escaped zoo animal remained at large in the surrounding forest for several hours.",    example2Kr: "탈출한 동물원 동물은 몇 시간 동안 주변 숲 속에서 도주 중이었다." },
  '201_13': { example2: "With exams at hand, students are spending late nights reviewing all of their notes.",      example2Kr: "시험이 임박하자 학생들은 모든 노트를 복습하며 늦은 밤을 보내고 있다." },
  '201_14': { example2: "At heart, she remains a creative artist even though she now works in corporate finance.",  example2Kr: "마음속으로는, 그녀가 지금 기업 재무에서 일하고 있지만 창의적인 예술가로 남아 있다." },
  '201_15': { example2: "The witness described every detail of the incident at length to the investigating officers.", example2Kr: "증인은 수사 담당자들에게 사건의 모든 세부 사항을 자세히 설명했다." },
  '201_16': { example2: "When the question was posed in French, the student was completely at a loss.",             example2Kr: "질문이 프랑스어로 제시되었을 때, 학생은 완전히 어쩔 줄 몰랐다." },
  '201_17': { example2: "Deep breathing exercises can help put anxious speakers at ease before a presentation.",    example2Kr: "심호흡 운동이 발표 전에 불안한 발표자들을 편안하게 하는 데 도움이 된다." },
  '201_18': { example2: "Without new investment, the company can at best maintain its current market share.",       example2Kr: "새로운 투자 없이는 회사가 기껏해야 현재의 시장 점유율을 유지할 수 있다." },
  '201_19': { example2: "At worst, the software glitch will require a full system restart to be resolved.",         example2Kr: "최악의 경우, 소프트웨어 결함을 해결하려면 전체 시스템을 재시작해야 할 것이다." },

  // Day 202 — 전치사 ON
  '202_0':  { example2: "Delivering the presentation on time showed the client that we respect their schedule.",    example2Kr: "제시간에 발표를 전달한 것이 우리가 고객의 일정을 존중한다는 것을 보여주었다." },
  '202_1':  { example2: "She left the door unlocked on purpose so that her roommate could get in easily.",          example2Kr: "그녀는 룸메이트가 쉽게 들어올 수 있도록 의도적으로 문을 잠그지 않았다." },
  '202_2':  { example2: "On the whole, the transition to the new software system went more smoothly than expected.", example2Kr: "전반적으로, 새 소프트웨어 시스템으로의 전환은 예상보다 더 원활하게 진행되었다." },
  '202_3':  { example2: "The CEO presented the award on behalf of the entire software development team.",           example2Kr: "CEO가 전체 소프트웨어 개발팀을 대신하여 상을 수여했다." },
  '202_4':  { example2: "The treatment did not make him feel worse; on the contrary, he improved visibly.",         example2Kr: "치료가 그를 더 안 좋게 만들지 않았다; 오히려 그는 눈에 띄게 호전되었다." },
  '202_5':  { example2: "Exploring a new city on foot is the best way to discover its hidden gems.",               example2Kr: "새 도시를 걸어서 탐험하는 것이 숨겨진 보석들을 발견하는 가장 좋은 방법이다." },
  '202_6':  { example2: "All summer clothing will go on sale at the end of August to clear seasonal stock.",        example2Kr: "계절 재고를 정리하기 위해 모든 여름 의류가 8월 말에 할인에 들어갈 것이다." },
  '202_7':  { example2: "A security guard is on duty around the clock at the main entrance of the building.",       example2Kr: "건물 정문에는 보안 요원이 24시간 내내 근무하고 있다." },
  '202_8':  { example2: "The new printing system produces customised books on demand, reducing warehouse costs.",   example2Kr: "새 인쇄 시스템은 주문에 따라 맞춤형 책을 생산하여 창고 비용을 줄인다." },
  '202_9':  { example2: "We spotted a beautiful waterfall on the way up to the mountain summit.",                   example2Kr: "우리는 산 정상으로 올라가는 길에 아름다운 폭포를 발견했다." },
  '202_10': { example2: "Solar energy is environmentally clean; on the other hand, installation costs remain high.", example2Kr: "태양 에너지는 환경적으로 깨끗하지만, 반면에 설치 비용은 여전히 높다." },
  '202_11': { example2: "Air traffic controllers went on strike, causing widespread flight cancellations across Europe.", example2Kr: "항공 교통 관제사들이 파업에 돌입하여 유럽 전역에 대규모 항공편 취소가 발생했다." },
  '202_12': { example2: "A revolutionary new drug therapy is currently on trial at three major hospitals in the country.", example2Kr: "혁신적인 신약 치료법이 현재 국내 세 개 주요 병원에서 임상 시험 중이다." },
  '202_13': { example2: "The outdoor rally was relocated indoors on account of the unexpected heavy snowfall.",     example2Kr: "야외 집회는 예상치 못한 폭설 때문에 실내로 장소가 변경되었다." },
  '202_14': { example2: "He eats breakfast on the go every morning because he always runs a little late.",          example2Kr: "그는 항상 조금 늦기 때문에 매일 아침 이동하면서 아침을 먹는다." },
  '202_15': { example2: "The manager made the critical decision on the spot without needing further consultation.", example2Kr: "관리자는 추가 상담이 필요 없이 즉석에서 중요한 결정을 내렸다." },
  '202_16': { example2: "The children were on edge all morning, anxiously waiting to find out their test results.",  example2Kr: "아이들은 시험 결과를 알기 위해 불안하게 기다리며 오전 내내 초조했다." },
  '202_17': { example2: "Phase two of the highway expansion project is running on schedule and within budget.",      example2Kr: "고속도로 확장 프로젝트의 2단계가 예정대로 예산 내에서 진행되고 있다." },
  '202_18': { example2: "On average, it takes about 66 days to form a new habit consistently, not 21.",             example2Kr: "평균적으로, 새로운 습관을 일관되게 형성하는 데는 21일이 아닌 약 66일이 걸린다." },
  '202_19': { example2: "On second thought, I will take the earlier flight to avoid any risky connection times.",   example2Kr: "다시 생각해보니, 위험한 환승 시간을 피하기 위해 더 이른 항공편을 탈 것이다." },

  // Day 203 — 전치사 IN
  '203_0':  { example2: "Contact the embassy in advance to find out exactly what documents are required for entry.", example2Kr: "입국에 필요한 서류를 정확히 알아보기 위해 사전에 대사관에 연락하세요." },
  '203_1':  { example2: "In addition to completing the training, new drivers must also pass a practical road test.", example2Kr: "교육 이수 외에도 신규 운전자들은 실기 도로 시험도 통과해야 한다." },
  '203_2':  { example2: "The ancient painting was, in fact, a clever forgery that fooled art museums for decades.", example2Kr: "그 고대 그림은 사실 수십 년 동안 미술관을 속인 교묘한 위작이었다." },
  '203_3':  { example2: "In general, people who sleep well consistently tend to perform better at cognitive tasks.", example2Kr: "일반적으로, 잠을 충분히 자는 사람들이 인지적 과제에서 더 잘 수행하는 경향이 있다." },
  '203_4':  { example2: "The two rival companies actually have more in common than their leaders publicly admit.",   example2Kr: "두 경쟁 회사는 사실 경영진이 공개적으로 인정하는 것보다 공통점이 더 많다." },
  '203_5':  { example2: "The senior nurse was left in charge of the entire ward when the doctor was called away.",  example2Kr: "의사가 불려 나가자 수석 간호사가 전체 병동을 맡게 되었다." },
  '203_6':  { example2: "Could you explain your entire research methodology in detail for the committee please?",   example2Kr: "위원회를 위해 전체 연구 방법론을 자세히 설명해 주시겠어요?" },
  '203_7':  { example2: "New emissions rules will be in effect across the entire transport sector from next year.",  example2Kr: "새 배출 규정이 내년부터 전체 운송 부문에 걸쳐 유효하게 된다." },
  '203_8':  { example2: "Better nutrition leads to improved health, which in turn boosts productivity at work.",     example2Kr: "더 나은 영양은 건강 향상으로 이어지고, 이는 결과적으로 업무 생산성을 높인다." },
  '203_9':  { example2: "In terms of environmental impact, cycling is superior to any form of motorised transport.", example2Kr: "환경적 영향 측면에서 자전거 타기는 어떤 형태의 자동차 교통보다 우수하다." },
  '203_10': { example2: "In order to qualify, all candidates must hold a relevant degree and three years' experience.", example2Kr: "자격을 갖추려면 모든 지원자들이 관련 학위와 3년間의 경력을 보유해야 한다." },
  '203_11': { example2: "Eliminating processed foods from the diet is difficult at first but rewarding in the long run.", example2Kr: "가공식품을 식단에서 제거하는 것은 처음에는 어렵지만 장기적으로는 보람 있다." },
  '203_12': { example2: "Northern summers are short and intense; in contrast, the south enjoys a much longer season.", example2Kr: "북부의 여름은 짧고 강렬하다; 대조적으로, 남부는 훨씬 더 긴 계절을 즐긴다." },
  '203_13': { example2: "In brief, our recommendation is to expand into the Asian market during next quarter.",      example2Kr: "간략히, 저희의 권고는 다음 분기에 아시아 시장으로 확장하는 것입니다." },
  '203_14': { example2: "If in doubt about the authenticity of an email, do not click any of the embedded links.",  example2Kr: "이메일의 진위 여부에 의심이 가면, 포함된 링크 중 어느 것도 클릭하지 마세요." },
  '203_15': { example2: "Peace negotiations between the two nations are currently in progress in Geneva.",           example2Kr: "두 국가 사이의 평화 협상이 현재 제네바에서 진행 중이다." },
  '203_16': { example2: "The airline found itself in trouble when passengers began filing mass compensation claims.", example2Kr: "승객들이 대규모 보상 청구를 시작하자 항공사는 곤경에 처하게 되었다." },
  '203_17': { example2: "Local charities distribute emergency food parcels to families in need every single week.",  example2Kr: "지역 자선단체들이 매주 도움이 필요한 가족들에게 긴급 식품 꾸러미를 나눠준다." },
  '203_18': { example2: "All emergency procedures must be in place before the new facility can open to the public.", example2Kr: "모든 비상 절차가 갖춰져야 새 시설이 대중에게 개방될 수 있다." },
  '203_19': { example2: "In theory, working from home increases productivity; in practice, results vary greatly.",   example2Kr: "이론적으로는 재택근무가 생산성을 높이지만, 실제로는 결과가 크게 다르다." },

  // Day 204 — 전치사 FOR & TO
  '204_0':  { example2: "New users can access all the premium features completely for free during the first month.", example2Kr: "새 사용자들은 첫 달 동안 모든 프리미엄 기능에 완전히 무료로 접근할 수 있다." },
  '204_1':  { example2: "He gave up smoking for good after the doctor warned him about his deteriorating heart condition.", example2Kr: "의사가 악화되는 심장 질환에 대해 경고한 후 그는 영원히 흡연을 끊었다." },
  '204_2':  { example2: "Travellers often take passport freedom for granted until they face strict visa restrictions.", example2Kr: "여행자들은 엄격한 비자 제한에 직면할 때까지 여권 자유를 당연하게 여기는 경우가 많다." },
  '204_3':  { example2: "Mindfulness practices, for instance meditation and slow breathing, reduce anxiety effectively.", example2Kr: "예를 들어 명상과 느린 호흡 같은 마음챙김 연습이 불안을 효과적으로 줄인다." },
  '204_4':  { example2: "For now, the border remains open, though the political situation may change swiftly.",       example2Kr: "당분간은 국경이 열려 있지만, 정치적 상황은 신속하게 변할 수 있다." },
  '204_5':  { example2: "For the time being, we will continue using the old system until the upgrade is complete.",  example2Kr: "당분간, 업그레이드가 완료될 때까지 기존 시스템을 계속 사용할 것이다." },
  '204_6':  { example2: "For once, the coach had nothing to criticise after the team's truly flawless performance.", example2Kr: "이번만은, 팀의 진정으로 흠잡을 데 없는 경기 후 코치가 비판할 것이 없었다." },
  '204_7':  { example2: "We cannot finalise the plans for sure until the investor officially confirms the funding.",  example2Kr: "투자자가 공식적으로 자금을 확인할 때까지 계획을 확실히 결정할 수 없다." },
  '204_8':  { example2: "I haven't been to the theatre for ages — probably not since long before the lockdown.",     example2Kr: "극장에 간 지 오랫동안 됐다 — 아마 봉쇄 훨씬 전부터 안 간 것 같다." },
  '204_9':  { example2: "This time the champion made it clear she was returning to the sport for keeps.",            example2Kr: "이번에 챔피언은 자신이 그 스포츠에 영구적으로 복귀한다는 것을 분명히 했다." },
  '204_10': { example2: "To date, more than fifty countries have ratified the landmark international climate accord.", example2Kr: "현재까지 50개 이상의 국가가 역사적인 국제 기후 협약을 비준했다." },
  '204_11': { example2: "To begin with, review all the existing data carefully before proposing any new solutions.",  example2Kr: "우선 새로운 해결책을 제안하기 전에 기존의 모든 데이터를 신중하게 검토하라." },
  '204_12': { example2: "The director's instructions were firm and to the point: finish the report by Friday noon.", example2Kr: "감독의 지시는 확고하고 요점에 맞았다: 금요일 정오까지 보고서를 끝내라." },
  '204_13': { example2: "The engineers rebooted the server multiple times to no avail before discovering the fault.", example2Kr: "엔지니어들이 결함을 발견하기 전에 서버를 여러 번 재부팅했지만 소용없었다." },
  '204_14': { example2: "To some extent, luck plays a role in career success, but consistent preparation matters more.", example2Kr: "어느 정도는, 운이 경력 성공에 역할을 하지만, 일관된 준비가 더 중요하다." },
  '204_15': { example2: "To the scientists' surprise, the plant continued to grow without any sunlight for two weeks.", example2Kr: "과학자들의 놀라움에도, 식물은 2주 동안 햇빛 없이 계속 자랐다." },
  '204_16': { example2: "To the manager's knowledge, no confidential data was ever shared outside the organisation.",  example2Kr: "관리자가 아는 한, 기밀 데이터는 조직 외부에 공유된 적이 없다." },
  '204_17': { example2: "He is meticulous to a fault, checking every single line of code before making a submission.", example2Kr: "그는 지나칠 정도로 꼼꼼하여 제출하기 전에 모든 코드 한 줄씩 확인한다." },
  '204_18': { example2: "Waking up to find the entire production database had been deleted was alarming, to say the least.", example2Kr: "전체 운영 데이터베이스가 삭제된 것을 알게 되는 것은 최소한으로 말해도 충격적이었다." },
  '204_19': { example2: "The public apology made things worse, and to make matters worse, sales also dropped sharply.", example2Kr: "공개 사과가 상황을 악화시켰고, 설상가상으로 매출도 급격히 떨어졌다." },

  // Day 205 — 전치사 BY / WITH / FROM
  '205_0':  { example2: "She ran into her old school friend by chance in a small independent bookshop in Edinburgh.", example2Kr: "그녀는 에든버러의 작은 독립 서점에서 우연히 옛 학교 친구를 만났다." },
  '205_1':  { example2: "This year's harvest is by far the largest that the agricultural region has recorded in decades.", example2Kr: "올해 수확량은 단연코 그 농업 지역이 수십 년 만에 기록한 가장 많은 양이다." },
  '205_2':  { example2: "Learning poetry by heart sharpens memory and deepens an appreciation of language.",          example2Kr: "시를 암기하는 것은 기억력을 날카롭게 하고 언어에 대한 감각을 깊게 한다." },
  '205_3':  { example2: "The technician accidentally deleted the entire production database by mistake, causing a major outage.", example2Kr: "기술자가 실수로 전체 운영 데이터베이스를 삭제하여 대규모 중단이 발생했다." },
  '205_4':  { example2: "The discovery of a single fossil is by no means sufficient evidence for classifying a new species.", example2Kr: "단 하나의 화석 발견은 새 종을 분류하기 위한 충분한 증거가 결코 아니다." },
  '205_5':  { example2: "If you would like to raise any concerns publicly at today's meeting, by all means do so.",   example2Kr: "오늘 회의에서 어떤 우려 사항이든 공개적으로 제기하고 싶다면 물론 그렇게 하세요." },
  '205_6':  { example2: "By now, the package should have arrived; please check your online tracking number.",         example2Kr: "지금쯤은 소포가 도착했을 것이니, 온라인 추적 번호를 확인하세요." },
  '205_7':  { example2: "The museum curator restored the heavily damaged oil painting with extraordinary care.",      example2Kr: "박물관 큐레이터는 심하게 손상된 유화를 특별한 주의를 기울여 복원했다." },
  '205_8':  { example2: "Thanks to months of intense practice, she delivered her entire keynote speech with ease.",   example2Kr: "몇 달간의 집중적인 연습 덕분에 그녀는 전체 기조연설을 수월하게 전달했다." },
  '205_9':  { example2: "With regard to the invoice discrepancy, our accounts team is investigating and will respond soon.", example2Kr: "청구서 불일치에 관하여, 우리 회계팀이 조사 중이며 곧 답변할 것이다." },
  '205_10': { example2: "With respect to the proposed merger, the full board will vote at the next scheduled meeting.", example2Kr: "제안된 합병에 관하여, 전체 이사회가 다음 예정된 회의에서 투표할 것이다." },
  '205_11': { example2: "The new vaccine is without doubt a landmark breakthrough in fighting infectious diseases.",    example2Kr: "새 백신은 의심할 여지 없이 전염병과의 싸움에서 획기적인 돌파구이다." },
  '205_12': { example2: "All quality control checks must be completed without fail before every product shipment.",   example2Kr: "품질 관리 점검은 모든 제품 출하 전에 반드시 완료되어야 한다." },
  '205_13': { example2: "After months of rigorous preparation, the candidate passed the bar exam with flying colors.", example2Kr: "몇 달간의 엄격한 준비 끝에, 지원자는 변호사 시험에 눈부신 성과로 합격했다." },
  '205_14': { example2: "From now on, any decision above a certain budget limit will require full board approval.",   example2Kr: "이제부터, 특정 예산 한도 이상의 모든 결정은 전체 이사회의 승인이 필요하다." },
  '205_15': { example2: "The development team rewrote the entire codebase completely from scratch to remove legacy bugs.", example2Kr: "개발팀이 레거시 버그를 제거하기 위해 전체 코드베이스를 처음부터 완전히 다시 작성했다." },
  '205_16': { example2: "From time to time, unexpected opportunities arise that can completely change your career path.", example2Kr: "때때로, 당신의 경력 경로를 완전히 바꿀 수 있는 예상치 못한 기회들이 나타난다." },
  '205_17': { example2: "The athlete was dressed proudly in the national team's colours from head to toe on match day.", example2Kr: "선수는 경기일에 머리부터 발끝까지 국가대표팀 색깔로 자랑스럽게 차려입었다." },
  '205_18': { example2: "Apart from the weather, everything about our holiday in Japan was absolutely perfect.",       example2Kr: "날씨를 제외하고, 일본에서의 우리 휴가의 모든 것이 완전히 완벽했다." },
  '205_19': { example2: "The final exam results were far from what the students had hoped for after all their revision.", example2Kr: "최종 시험 결과는 모든 복습을 한 후 학생들이 기대했던 것과는 전혀 달랐다." },

  // ── Day 206: OVER / UNDER / ABOVE / BELOW ──
  '206_0':  { example2: "Over time, consistent daily habits compound into extraordinary long-term achievements.",             example2Kr: "시간이 지나면서, 꾸준한 일일 습관들이 축적되어 놀라운 장기적 성과로 이어진다." },
  '206_1':  { example2: "The coach made the players rehearse the same defensive drill over and over until it was automatic.", example2Kr: "코치는 선수들이 같은 수비 훈련을 자동으로 될 때까지 반복해서 연습시켰다." },
  '206_2':  { example2: "The entire neighbourhood was over the moon when the local team won the regional championship.",      example2Kr: "지역 팀이 지역 챔피언십에서 우승했을 때 온 동네가 몹시 기뻐했다." },
  '206_3':  { example2: "Skilled athletes train themselves to perform at their best even under pressure situations.",          example2Kr: "숙련된 운동선수들은 압박을 받는 상황에서도 최상의 성과를 낼 수 있도록 스스로를 훈련한다." },
  '206_4':  { example2: "Construction of the new bridge is well under way and expected to be completed before winter.",        example2Kr: "새 다리 건설이 한창 진행 중이며 겨울 전에 완공될 것으로 예상된다." },
  '206_5':  { example2: "By the time the ambulance arrived, the paramedic had already brought the situation under control.",   example2Kr: "구급차가 도착했을 때, 구급대원은 이미 상황을 제어 중이었다." },
  '206_6':  { example2: "Above all, the parents emphasised the importance of kindness and empathy to their children.",         example2Kr: "무엇보다도, 부모님은 자녀들에게 친절함과 공감의 중요성을 강조했다." },
  '206_7':  { example2: "The student's test scores were above average in every subject, earning her a scholarship.",           example2Kr: "그 학생의 시험 점수는 모든 과목에서 평균 이상이었고, 장학금을 받았다." },
  '206_8':  { example2: "All our business dealings are completely above board and subject to independent auditing.",           example2Kr: "우리의 모든 사업 거래는 완전히 공정하며 독립적인 감사를 받는다." },
  '206_9':  { example2: "The mountain roads became dangerous as temperatures plunged well below zero after sunset.",           example2Kr: "일몰 후 기온이 영하로 곤두박질치면서 산악 도로가 위험해졌다." },
  '206_10': { example2: "The department's productivity ratings remained below average for the entire first half of the year.", example2Kr: "그 부서의 생산성 점수는 상반기 내내 평균 이하를 유지했다." },
  '206_11': { example2: "Below the surface of the seemingly successful company lay serious cash-flow problems.",               example2Kr: "겉으로 성공적으로 보이는 회사의 표면 아래에는 심각한 현금 흐름 문제가 숨어 있었다." },
  '206_12': { example2: "The party planner admitted that the decorations had gone slightly over the top but it was fun.",      example2Kr: "파티 기획자는 장식이 약간 과도했다고 인정했지만 즐거웠다." },
  '206_13': { example2: "Common cold medicine is available over the counter and does not require a doctor's prescription.",    example2Kr: "일반 감기약은 처방전 없이 구입 가능하며 의사의 처방전이 필요하지 않다." },
  '206_14': { example2: "She called in sick, explaining that she was under the weather and needed a day to recover.",          example2Kr: "그녀는 몸이 안 좋아 회복을 위해 하루가 필요하다고 설명하며 병가를 냈다." },
  '206_15': { example2: "The innovative art movement operated under the radar for years before gaining mainstream recognition.", example2Kr: "그 혁신적인 예술 운동은 주류의 인정을 받기 전 수년 동안 주목받지 못하며 활동했다." },
  '206_16': { example2: "The volunteer went above and beyond, donating not just money but also her time and expertise.",        example2Kr: "그 자원봉사자는 기대 이상으로 노력하여 돈뿐만 아니라 시간과 전문 지식도 기부했다." },
  '206_17': { example2: "As the elected representative, he must remain completely above suspicion in all financial dealings.",  example2Kr: "선출된 대표로서, 그는 모든 재무 거래에서 완전히 의심할 여지가 없어야 한다." },
  '206_18': { example2: "The substitute player's performance was clearly below par and he was substituted at half-time.",       example2Kr: "교체 선수의 경기력이 명백히 기준 이하여서 그는 전반이 끝날 때 교체되었다." },
  '206_19': { example2: "Bringing up personal matters during a professional evaluation is entirely below the belt.",            example2Kr: "전문적인 평가 중에 개인적인 문제를 제기하는 것은 완전히 치사한 행동이다." },

  // ── Day 207: BETWEEN / AMONG / AROUND ──
  '207_0':  { example2: "A skilled diplomat knows how to read between the lines of every official government statement.",       example2Kr: "숙련된 외교관은 모든 공식 정부 성명의 행간을 읽는 방법을 안다." },
  '207_1':  { example2: "Between you and me, the company is planning to relocate its headquarters to another city.",            example2Kr: "우리끼리 얘기지만, 회사는 본사를 다른 도시로 이전할 계획이다." },
  '207_2':  { example2: "While between jobs, he volunteered abroad and gained invaluable cross-cultural experience.",           example2Kr: "이직하는 사이에, 그는 해외에서 자원봉사를 하며 귀중한 이문화 경험을 쌓았다." },
  '207_3':  { example2: "The conference had two keynote speeches with breakout workshops in between each session.",             example2Kr: "그 회의에는 두 개의 기조연설이 있었고 각 세션 사이에 분과 워크숍이 있었다." },
  '207_4':  { example2: "Among others, the committee praised the initiative's effectiveness in reducing urban pollution.",       example2Kr: "그 중에서도, 위원회는 도시 오염 감소에 있어 이 이니셔티브의 효과성을 칭찬했다." },
  '207_5':  { example2: "The school's drama programme is consistently ranked among the best in the entire district.",           example2Kr: "그 학교의 드라마 프로그램은 전체 지구에서 최고 수준에 꾸준히 선정된다." },
  '207_6':  { example2: "The directors settled the dispute among themselves without involving external legal counsel.",          example2Kr: "이사들은 외부 법률 고문을 개입시키지 않고 그들끼리 분쟁을 해결했다." },
  '207_7':  { example2: "She is numbered among the most influential policy makers of her generation in this country.",          example2Kr: "그녀는 이 나라에서 자신의 세대에서 가장 영향력 있는 정책 입안자 중 한 명으로 꼽힌다." },
  '207_8':  { example2: "The emergency medical team worked tirelessly around the clock to care for disaster survivors.",        example2Kr: "비상 의료팀은 재난 생존자들을 돌보기 위해 24시간 내내 지치지 않고 일했다." },
  '207_9':  { example2: "With summer around the corner, the tourism board is launching an international marketing campaign.",   example2Kr: "여름이 코앞에 다가오면서, 관광청이 국제 마케팅 캠페인을 시작하고 있다." },
  '207_10': { example2: "It is nearly impossible to get around the strict data privacy laws that govern digital platforms.",     example2Kr: "디지털 플랫폼을 규율하는 엄격한 데이터 개인정보 보호법을 피해 나가기는 거의 불가능하다." },
  '207_11': { example2: "The experienced CEO managed to turn around the company's fortunes within just eighteen months.",        example2Kr: "경험 많은 CEO는 단 18개월 만에 회사의 운명을 반전시키는 데 성공했다." },
  '207_12': { example2: "Communication between and among regional offices improved after the new intranet platform launched.",  example2Kr: "새 인트라넷 플랫폼이 출시된 후 지역 사무소 간 및 내부 소통이 향상되었다." },
  '207_13': { example2: "The consultant estimated costs at somewhere around fifty thousand dollars for the full renovation.",    example2Kr: "컨설턴트는 전체 수리 비용을 약 5만 달러로 추정했다." },
  '207_14': { example2: "The spring term starts right around the fourteenth of April, so register before then.",                example2Kr: "춘계 학기가 4월 14일쯤에 시작하니, 그 전에 등록하세요." },
  '207_15': { example2: "She refused to let ambition come between her closest friends and her lifelong values.",                example2Kr: "그녀는 야망이 가장 친한 친구들과 자신의 평생 가치관 사이를 방해하도록 두지 않았다." },
  '207_16': { example2: "New financial regulations affect everyone — do not assume any company can fall among exceptions.",      example2Kr: "새 금융 규정은 모두에게 적용됩니다 — 어떤 회사도 예외에 끼일 수 있다고 가정하지 마세요." },
  '207_17': { example2: "The ancient tree roots are deeply wrapped around the foundations of the old stone church.",            example2Kr: "고대 나무 뿌리들이 오래된 석조 교회 기초 주위에 깊게 감겨 있다." },
  '207_18': { example2: "The bonus should be spread among all team members who contributed to the project equally.",            example2Kr: "보너스는 프로젝트에 기여한 모든 팀원들에게 고르게 배분되어야 한다." },
  '207_19': { example2: "The motivational speaker travels round around the country inspiring students in rural areas.",         example2Kr: "그 동기 부여 강연자는 농촌 지역의 학생들에게 영감을 주며 전국을 이리저리 다닌다." },

  // ── Day 208: BEFORE / AFTER / DURING ──
  '208_0':  { example2: "Master the fundamentals now and before long you will handle complex challenges with confidence.",      example2Kr: "지금 기초를 익혀두면, 머지않아 복잡한 도전도 자신 있게 다룰 수 있을 것이다." },
  '208_1':  { example2: "Confirm your dietary requirements beforehand so the catering team can make proper arrangements.",      example2Kr: "케이터링팀이 적절한 준비를 할 수 있도록 사전에 식이 요건을 확인해 주세요." },
  '208_2':  { example2: "Never before had the city hosted such a large-scale international sporting event of this magnitude.",  example2Kr: "이 도시가 이처럼 대규모의 국제 스포츠 행사를 개최한 적은 이전에 한 번도 없었다." },
  '208_3':  { example2: "Double-check all the data right before submitting the final report to avoid costly errors.",           example2Kr: "비용이 많이 드는 오류를 피하기 위해 최종 보고서를 제출하기 바로 전에 모든 데이터를 재확인하세요." },
  '208_4':  { example2: "The negotiators reached a preliminary agreement just before talks were scheduled to break down.",      example2Kr: "협상가들은 회담이 결렬될 예정이기 바로 직전에 예비 합의에 도달했다." },
  '208_5':  { example2: "After all the delays and setbacks, the completed bridge was a source of immense civic pride.",         example2Kr: "모든 지연과 차질 끝에, 완공된 다리는 엄청난 시민 자부심의 원천이 되었다." },
  '208_6':  { example2: "Many creative professionals do their most productive work after hours when the office is quiet.",      example2Kr: "많은 창의적인 전문가들은 사무실이 조용한 업무 시간 후에 가장 생산적인 작업을 한다." },
  '208_7':  { example2: "Soon after completing the intensive training programme, she was promoted to team leader.",             example2Kr: "집중 교육 프로그램을 완료한 후 얼마 지나지 않아, 그녀는 팀 리더로 승진했다." },
  '208_8':  { example2: "New challenges emerged one after another as the company expanded into unfamiliar overseas markets.",   example2Kr: "회사가 낯선 해외 시장으로 진출하면서 새로운 도전이 잇달아 나타났다." },
  '208_9':  { example2: "He asked a trusted colleague to look after his important clients while he was on medical leave.",      example2Kr: "그는 의료 휴가 중에 중요한 고객들을 돌봐달라고 신뢰하는 동료에게 부탁했다." },
  '208_10': { example2: "Quiet study areas are available for students to use during the day between scheduled classes.",        example2Kr: "조용한 학습 공간이 예정된 수업 사이에 낮 동안 학생들이 이용할 수 있도록 마련되어 있다." },
  '208_11': { example2: "The office remains open during the week but closes completely for the weekend and public holidays.",   example2Kr: "사무실은 주중에는 열려 있지만 주말과 공휴일에는 완전히 문을 닫는다." },
  '208_12': { example2: "During that time, the research division attracted significant international investment and attention.",  example2Kr: "그 기간 동안, 연구 부서는 상당한 국제 투자와 관심을 끌었다." },
  '208_13': { example2: "At some point during the board meeting, both sides finally agreed on the core budget allocation.",     example2Kr: "이사회 회의 중 어느 시점에, 양측은 핵심 예산 배분에 대해 마침내 합의했다." },
  '208_14': { example2: "During one's lifetime, the relationships you build often matter more than career achievements.",        example2Kr: "일생 동안, 당신이 구축하는 인간관계는 종종 직업적 성취보다 더 중요하다." },
  '208_15': { example2: "The before and after comparison clearly illustrated the enormous impact of the rebranding effort.",    example2Kr: "전후 비교는 리브랜딩 노력의 엄청난 영향을 명확하게 보여주었다." },
  '208_16': { example2: "Complaining about the decision after the fact solves nothing — let us focus on moving forward.",       example2Kr: "사후에 결정에 대해 불평하는 것은 아무것도 해결하지 못합니다 — 앞으로 나아가는 데 집중합시다." },
  '208_17': { example2: "Several key stakeholders changed positions during the course of the lengthy contract negotiation.",    example2Kr: "긴 계약 협상 과정에서 몇몇 핵심 이해관계자들이 입장을 바꿨다." },
  '208_18': { example2: "Start saving small amounts consistently and before you know it, you will have a solid emergency fund.", example2Kr: "꾸준히 소액을 저축하기 시작하면 어느새 든든한 비상자금이 마련될 것이다." },
  '208_19': { example2: "After a while, the initial difficulties of living abroad begin to feel like normal everyday life.",     example2Kr: "잠시 후에, 해외 생활의 초기 어려움들이 일상적인 삶처럼 느껴지기 시작한다." },

  // ── Day 209: THROUGH / ACROSS / ALONG ──
  '209_0':  { example2: "Every applicant must go through a detailed skills assessment before the interview process begins.",    example2Kr: "모든 지원자는 면접 과정이 시작되기 전에 상세한 기술 평가를 통과해야 한다." },
  '209_1':  { example2: "He was a loyal supporter of the club through and through, never missing a single home game.",          example2Kr: "그는 단 한 번의 홈 경기도 빠지지 않은 속속들이 충성스러운 클럽 지지자였다." },
  '209_2':  { example2: "It was hard work, but the junior analyst managed to get through her first audit assignment alone.",    example2Kr: "힘든 일이었지만, 주니어 분석가는 첫 번째 감사 업무를 혼자서 해낼 수 있었다." },
  '209_3':  { example2: "Experienced investors can see through misleading financial reports and identify the real value.",       example2Kr: "경험 많은 투자자들은 오해를 불러일으키는 재무 보고서를 꿰뚫어 보고 실제 가치를 파악할 수 있다." },
  '209_4':  { example2: "The planned acquisition fell through when regulators refused to approve the merger proposal.",          example2Kr: "규제 당국이 합병 제안 승인을 거부하면서 계획된 인수가 무산되었다." },
  '209_5':  { example2: "By chance, he came across a rare first edition of the novel at a small second-hand bookshop.",         example2Kr: "우연히, 그는 작은 중고 서점에서 소설의 귀한 초판을 발견했다." },
  '209_6':  { example2: "The budget cuts affected all divisions across the board, including the research and development team.", example2Kr: "예산 삭감은 연구개발팀을 포함하여 모든 부서에 전반적으로 영향을 미쳤다." },
  '209_7':  { example2: "The key challenge of any presentation is to get the core message across clearly and memorably.",        example2Kr: "모든 프레젠테이션의 핵심 과제는 핵심 메시지를 명확하고 기억에 남도록 전달하는 것이다." },
  '209_8':  { example2: "The product recall alert was issued to all consumers across the country via official media channels.", example2Kr: "제품 리콜 경보가 공식 미디어 채널을 통해 전국의 모든 소비자들에게 발행되었다." },
  '209_9':  { example2: "Great storytelling cuts across generational divides and connects audiences of all ages and backgrounds.", example2Kr: "훌륭한 스토리텔링은 세대 간 장벽을 초월하여 모든 연령과 배경의 청중을 연결한다." },
  '209_10': { example2: "He made several key contacts along the way that eventually led to his breakthrough business deal.",     example2Kr: "그는 결국 획기적인 비즈니스 거래로 이어진 몇 가지 핵심 인맥을 도중에 쌓았다." },
  '209_11': { example2: "A once-in-a-decade partnership opportunity like this simply does not come along very often at all.",    example2Kr: "이처럼 10년에 한 번 있는 파트너십 기회는 아주 자주 찾아오지 않는다." },
  '209_12': { example2: "Despite the cultural differences, the entire team managed to get along exceptionally well together.",   example2Kr: "문화적 차이에도 불구하고, 전체 팀은 함께 매우 잘 지낼 수 있었다." },
  '209_13': { example2: "The proposed solution was a phased rollout — or something along those lines — to minimise disruption.", example2Kr: "제안된 해결책은 단계적 출시, 또는 그런 맥락의 무언가로 혼란을 최소화하는 것이었다." },
  '209_14': { example2: "Each participant was asked to bring along a recent example of their best professional work.",           example2Kr: "각 참가자는 자신의 최근 최고 전문 업무 사례를 함께 가져오도록 요청받았다." },
  '209_15': { example2: "True leaders always follow through on their commitments, however inconvenient or difficult it may be.", example2Kr: "진정한 리더는 아무리 불편하거나 어렵더라도 항상 자신의 약속을 끝까지 완수한다." },
  '209_16': { example2: "The viral social media post spread across all major platforms within just a few hours.",                example2Kr: "바이럴 소셜 미디어 게시물이 단 몇 시간 만에 모든 주요 플랫폼에 걸쳐 퍼졌다." },
  '209_17': { example2: "Let us move along to the final part of today's training and review the key learning outcomes.",         example2Kr: "오늘 교육의 마지막 부분으로 나아가 핵심 학습 성과를 검토합시다." },
  '209_18': { example2: "Halfway through the negotiation, the lead counsel requested a thirty-minute recess to consult.",       example2Kr: "협상 절반쯤에, 수석 자문은 협의를 위해 30분간의 휴회를 요청했다." },
  '209_19': { example2: "All shipments must pass through customs inspection before being cleared for domestic distribution.",    example2Kr: "모든 화물은 국내 유통 허가를 받기 전에 세관 검사를 통과해야 한다." },

  // ── Day 210: AGAINST / DESPITE / WITHOUT ──
  '210_0':  { example2: "Against all odds, the small local team beat the reigning national champions in sudden-death overtime.", example2Kr: "모든 역경을 딛고, 작은 지역 팀이 갑작스러운 연장전에서 현 전국 챔피언을 이겼다." },
  '210_1':  { example2: "Leaking confidential client data goes against every principle of professional responsibility.",          example2Kr: "기밀 고객 데이터를 유출하는 것은 전문적 책임의 모든 원칙에 반한다." },
  '210_2':  { example2: "Lack of sleep and poor nutrition work against achieving optimal cognitive performance.",                 example2Kr: "수면 부족과 불량한 영양 섭취는 최적의 인지 능력 달성에 불리하게 작용한다." },
  '210_3':  { example2: "Thousands of citizens stood against the proposed demolition of the century-old historic building.",     example2Kr: "수천 명의 시민들이 100년 된 역사적 건물의 제안된 철거에 반대 입장을 취했다." },
  '210_4':  { example2: "The aid workers found themselves up against impossible logistical challenges in the remote region.",    example2Kr: "구호 대원들은 오지 지역에서 불가능한 물류 도전에 직면하게 되었다." },
  '210_5':  { example2: "Despite everything she endured, she emerged stronger and more determined than ever before.",            example2Kr: "그녀가 겪은 모든 것에도 불구하고, 그녀는 그 어느 때보다 더 강하고 더 굳건하게 나아왔다." },
  '210_6':  { example2: "Despite the fact that the budget was reduced, the team delivered a remarkable final product.",         example2Kr: "예산이 삭감된 사실에도 불구하고, 팀은 놀라운 최종 결과물을 제공했다." },
  '210_7':  { example2: "She found herself nodding in agreement despite herself, as the argument was surprisingly compelling.",  example2Kr: "그 주장이 놀랍도록 설득력이 있어 자신도 모르게 고개를 끄덕이고 있는 자신을 발견했다." },
  '210_8':  { example2: "Despite appearances, the relaxed atmosphere concealed an incredibly intense competitive spirit.",       example2Kr: "겉보기와 달리, 여유로운 분위기 속에 믿을 수 없을 만큼 치열한 경쟁 정신이 숨겨져 있었다." },
  '210_9':  { example2: "Despite the odds, the debut filmmaker secured distribution deals in over forty countries worldwide.",   example2Kr: "불리한 상황에도 불구하고, 신인 영화 감독은 전 세계 40개국 이상에서 배급 계약을 확보했다." },
  '210_10': { example2: "Great leaders make swift decisions and embrace new challenges without hesitation.",                     example2Kr: "훌륭한 리더들은 망설임 없이 신속하게 결정을 내리고 새로운 도전을 받아들인다." },
  '210_11': { example2: "This chef's signature dish is without a doubt the most memorable item on the entire menu.",             example2Kr: "이 셰프의 시그니처 요리는 의심할 여지 없이 전체 메뉴에서 가장 기억에 남는 것이다." },
  '210_12': { example2: "The company terminated several contracts without notice, creating significant financial uncertainty.",   example2Kr: "회사는 여러 계약을 통보 없이 해지하여 상당한 재정적 불확실성을 야기했다." },
  '210_13': { example2: "She is without question the most experienced candidate we have ever seen for this senior position.",    example2Kr: "그녀는 의문의 여지 없이 우리가 이 고위직에서 본 가장 경험이 풍부한 지원자이다." },
  '210_14': { example2: "The new hygiene protocol must be followed by all kitchen staff without exception at all times.",        example2Kr: "새 위생 프로토콜은 모든 주방 직원이 예외 없이 항상 따라야 한다." },
  '210_15': { example2: "Her concern about the proposal was not without reason; independent experts raised similar doubts.",     example2Kr: "그 제안에 대한 그녀의 우려는 이유 없는 것이 아니었다; 독립적인 전문가들도 비슷한 의문을 제기했다." },
  '210_16': { example2: "Against the odds, the grassroots campaign raised enough funds to challenge the incumbent politician.",  example2Kr: "역경에 맞서, 그 풀뿌리 캠페인은 현직 정치인에게 도전하기에 충분한 자금을 모았다." },
  '210_17': { example2: "Despite all efforts by the mediation team, the labour dispute continued into its third month.",         example2Kr: "조정 팀의 모든 노력에도 불구하고, 노동 분쟁은 3개월째로 접어들었다." },
  '210_18': { example2: "The annual summit concluded without a hitch, with all delegations agreeing on a joint statement.",     example2Kr: "연례 정상회의가 모든 대표단이 공동 성명에 합의하며 차질 없이 마무리되었다." },
  '210_19': { example2: "Cutting corners on quality goes completely against the grain of everything this brand represents.",     example2Kr: "품질에서 지름길을 택하는 것은 이 브랜드가 나타내는 모든 것의 본성에 완전히 거슬린다." }
});
